apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: admin
    namespace: admin
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 15.7.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: admin
    values:
        ingress:
            main:
                annotations:
                    traefik.frontend.passHostHeader: "false"
                enabled: true
                hosts:
                    - host: admin.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        release_name: admin
        service:
            main:
                enabled: true
                externalIP: ${ADMIN_IP}
                ports:
                    main:
                        enabled: true
                        port: 8080
                        protocol: http
                type: ExternalIP
                useSlice: false
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main: {}
