apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ke6CzFJ+GeQy47673AQTGM+Ic9fqfFAwPUehhV+CZ5JzGwR0cGaD1rTbv9XR5Xxng4JFdY2wratgQWQeKTJPUJRFtYsBTYehX8XwuZR4XwaD1KT7MOgVUihAw3ih+NpOF1Xv57EbqtPZoWNY8Prv6+58CDvSvAUqlVKbar9ataz8l4qwoSbSxOsS8eeXgUcxndlPv7CPvXTzrrHUjlCd8OOorghimRMWOQoxipKTwoRe/6nv6sB7Kjgye5hzqjzF1WtjsHHQFKtTXLxXKBuY/O8AxIMOWswUv51yQTPPB45gmW2Ie5PuiZXa33gFBj7cRKaUcLCoP24gHj+vSVObbqFxzCiea0oDPKVBMLz6Il8AsvJYonD9GpVCNijwEq+8,iv:pAEInGsAGZbsQEIPwYzJCwnKOA3DWXtzon1JroEUj7I=,tag:bQUcPh6MHv2Xlk+DIA16Ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:HSZLErcpaXTA6Lm96Z5JS3NLHDqkd55w7fc4q4S0Dh+zSKHL9jrW9TzEM89qmi4H0AnRDxLf+n3lxmnPxMeXJ6F9V9VMEe+K27N8oUUmXUnZ5LDVl/v+L5HNxz4+XDW7/NvyuvR3tbnfOl1QCH1DsdFxMN49wtKgxEsrHWLp1DQgJ2JTRDgra58ewHsqcFX/gIgzL5epBQI1i17WZlOIsNHMF/XpiukwGAn5A6ut/WffYYI9WOGF4flSarYPHzCKtHv0bD5Sp5SvAefABg==,iv:d9a38WP06CJ9RDlivRcQ1RwaoYkebF+1H5m5maPL/+0=,tag:M9ANDQk1b1o1TwxdffNLew==,type:str]
    known_hosts: ENC[AES256_GCM,data:KE38qvMN94nhLJbDAshMPgcwJwHYIk+7SZRIRvoGf3FRwmdFv6LqUl7rK0kFTT8id5N6bpljXBc35lNVScTPS1jaOsIwMq14jEHYFn8sGTxt9hfwUvUQdPsWRcayfQPVlLb6OHvb1eU7Hp8+ThJt6hyE9ldJXnW72XDCC+ygPg0XOksGQCMHrEh/UYW+/K5PyT0tcmrgs30e3ybq5F2c9GgimF2dXatz1LiH,iv:Tp/nZVd20i+yLFP0ECAhGV6E863/RiWLeSsdg2k04eY=,tag:uEGDZwfy613NnClT4PWGqw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17xum3alc55s2l6khaqa2t8twq28cvdl92vfe37pvf69w6gq7rudqqxzu9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSFhKZDdaWGorVnJCOE55
            TEJ3NklIeDliTVpuclVGK3ZBVkp1aWc1NUVFCnpYQ1c1RHcwTmc0MGh0bUpDUEZz
            aUlIamk1M3VZbWFQY1NzZlhic2VUZlEKLS0tIHhUdjI1STMwK05xMmVuL1FMaXBZ
            cnVGMlpydW16U3p2UHgxNGR0cXhKMW8Kw3G5cCnRMTDOJfmzjCnvRbTKGpZZe3qH
            VxnwDjaLDvci7ju4IsaSfvJfMQvoioS/fDuh49ZoWtJG4NgH+Nlizw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-04T13:57:22Z"
    mac: ENC[AES256_GCM,data:sDpmy9Lyj3Q3o4Q2MU0/EGHu7bCgyErOjPMiRiMq3EQpbGLokBhwEVxSsdxXrVhXPfd6dF3jD6PjBHJJp62FVsCIGBbRJI3njVLrToP2lv+JveBE5TDwQwhrJ5XIUIGl1HuKrSf+J8wjFec3yeV5oN2s+RyOySUsl27Sg9d1f5Q=,iv:cI2UbFWN/AkjPmTZ3LToBd2vujE3/YzM+PYF0k6Rpvg=,tag:s00T5VOaxsKQ0/uZ5dj9bg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
