apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ENuhnTTkif8jiVnZcqCrh1fXpAiVbwELXMr90lUo9xLZcDDlbsNM8wnsfBGgWqREr46jRyR5aTU8GnXhZYchkJxvMNO3agGv6SdWQOsToJEINrV6Kbodp2GSMWoT9zUAc8iIlP3QA6wdJMJlUtYEPMIj59xqUJHZt/WqQn2hM2WvaTr798t17jSOone1NhDiZxxKReKuC46LFG7pKAxoKsBanQK0BHv3DMknirskILeOUGv0jKF0ifZkf7t5x+4drqjXgq83zmdz5Fd4j85NwBqvY8ex2cgoKoxGnMwtMr26qIznFhGVv6dvOS3hb+zxpvyRpt0F17B7DlZzXg7ikcOb6E0c/8wQHAnaBRFSjqKt6uLt/jQg6dKBwdz6NB+K,iv:9+W5z+/U7dUhxrTXiOgXoTsXEHn0uKrjaT7AfoIMY7E=,tag:bOrGQtYrycClZcivgUq1Fg==,type:str]
    identity.pub: ENC[AES256_GCM,data:nSANtlEpJUf87CuPtKq+ua1QxdmfFuhYoeOJR8mWaL7Bx7xFE3SycYl6024m9CKwLEnItJYYT54qa5C4uzZqiGu4oi9edXGvVG5MsmN9kcwQ8zUSFh4H36sbMlAFVS5slIHIog/FaBRTfq3cYDrKHcNja9Iuix2PYQsRjDAkyhzMowbJYq0Uwnpamg9EcCLX8aQQvg3X+X+r+iSya7E0JgXWuTfCqepnRSZQTsUPkypW9W1huCRoPTf6c3zMxumN7cxTc7LSgQBQch6XcA==,iv:p0OW0IKJYlLOdz5+In/C2Na5+3rJBHQjXR/pK3cC97g=,tag:qCl+PDiqps61n1cNYA4tGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:MDuDNuz8w3EpKVJCswo6TkTPGk2zPgKBuIH967m98RAAXwCojUyiTIPYADIe7C4wOnA5Ir+7F+K930g/03O6T5AdC1+NgU6JRPOAv5WL/3Gotg1+AM5AGyHATr0hk9CUdgg2C+u3UxBkEJ04YebD1GwO5sKzKZuDjharN1b/GvzDgba2QysjUgPJLoLc+icdV7ptW42xjZ3YcYBYtS87OEZVr0Y1yYF9EPNz,iv:9mzl5vXY6xiLbRwM/hwiXJqDE+/Xg7KlXkVCYPLZSH0=,tag:gOUgyi1lyu9yzkrqWkPgpw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17xum3alc55s2l6khaqa2t8twq28cvdl92vfe37pvf69w6gq7rudqqxzu9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdEJudmlxcFdDUVFwZGpj
            cVRZRnh4TWR3VUVmVDBhZmZpV2ZNenJjckg4CmNka3FCNDhkc05id2FPbG9LK1pF
            aGVEb0xTVERGbHhVQmJKdWUwREFCNEkKLS0tIG1rTzBxa2VXeVRrQTMzY2hOaDA0
            MnNkTFl2K2dQdS9Jam5zZzdlNkh5RU0KBHRsXW2kdh8jCwvY2+bOXyVRxBbEDCK1
            kAYezHYDJg27CJVeB9hh2kH/GHKwwR4u5inbd3IfbcUlt8lZLJW8Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T04:10:21Z"
    mac: ENC[AES256_GCM,data:li5ZUwLqZ4xA5VDs//VTiEtiWAx5TLzE0PzrFGT8kvRziUIImUHbF6p36S0wx+rQmD6jDEu9snv/eNLCBWd5bCU41KHCxnRk6cPuw5m3JaaBfAgBZkyaNtCtT+7emKr9ntSbb6haRf4kiqPXWDidP/uHkHjkHcljgM6bzYb4qvQ=,iv:YocoR5jXLLtRWhvDOb594dxdTlZwcBWx+NvnoQwSWoo=,tag:ZDM4xEqeyVZQMG64Yx2tow==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
