apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qaReMAcvpi8qqEZLmCnra/9FeN1QtBOTssL/AgQN6Q+h92NkDFZMYAzHgziRlGVD3XLQfETnaKPV+B2JkFGKQDJ/rhZL2c5R6OT1igtNHrJL5k6LTna5EehFHsUgNC3QyzXd1bQVuv6BP1BgDgz2cznZdlf9sN36qXL5oyXUgtfN0hGY5JwMTiGIJJPKybZkq2Fha8k1sRtebjQfTrk+fTzm1Agka/htUMxqNY+hX+U5n1pZl8VEj4sxW+1A8TGWMNfZ9mFBJLJIJpyvCPMHZWpCrq8RNF1LAgygQQzV8ujiuv56qAOD8jiOOc5oMjgs4/gdafqXANDatgDmNJ8AhYGxPkPorzGqAH318f2So3VvLbEcYdTuFNAqennzKpFy,iv:hAjbBMNSxpa6emHpHYPLdKwJa1lsGRLIkc+bLGlkufg=,tag:q8RLLJx+k+U1hENbVtxMgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:LSDvOmWl0OKyU6Jz/JUBu+KVkuc9xNDGTGRiZgmykVGJsQ6/zu7meUTCmzaaUo0ClYAtSMVcrcmJVaRKCBINEuth5Aut33wfKiO1hvYeVMURFqjoxh6aXRSUdnYdbqJix8BVxrksmwLltw1HtVSU7Mt7BmwWsaajkN21spQUwa79BTFepCQx8tgP5cUN4Y22q+VJiQ243+Se9dSA7DVYJYRtUfaUonQUYXRhaqwclW5BdEHqY8GDAgT3sgk1Guh7+nCmpubX2rYpy9ROig==,iv:taBPDvlsQZdOOSejYVrH1OptKOUXaZm/8Bi/neTNrAs=,tag:bjxlZe+eBjFy/ixi5fZ6jg==,type:str]
    known_hosts: ENC[AES256_GCM,data:oy58nnFbN16rI84X2HjfwKsQV9wZpEhoFxHKc8dzwQZNeWgxYyumeTFNo4MokFaW7Te3tt8Y4JOvc/CfROoWdfpictn4NY4gk+0hcA1J9J65T0qqguGf3zO+E7SXshmMZYzIi71DY/KNTa64negik3plzOnmX/y4F1ObgbahKjaudkg3kEo+zxoM/OlPEan47LDJz55UQKYKcpD18fEA8Sxm01uKKu8JBDAA,iv:iCU8NwuMXrOrC495YkPjl/wTxHcDBJzm7MP7Vn9Lmqk=,tag:mGQtmnKDOHz2Dyvi9IUYLw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17xum3alc55s2l6khaqa2t8twq28cvdl92vfe37pvf69w6gq7rudqqxzu9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbmY2TUlkalRieUpVVkFl
            bGxweDA3WnJ4dUhMeXN4Z1hvM0l4M2NweW0wCmlrMWpRVGJkNHgyQ2x1WVdwMUx1
            STBlYWc3Rm15U3ZPMlFXcGpjQnNhdFUKLS0tIHVXUHh4eDYyYkFQTDZHa0lPemJV
            NGorYmxpc1ZzOGtSTFdOeTR1OFVkNXcKslvTISn0FaEopIVgwlOGDlW8VyXWVYxs
            LqRHamXU0w9S2Z2OfpgIszyoT3ufkBymy2pg7KO8gAgYI347C/+yPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:45:25Z"
    mac: ENC[AES256_GCM,data:NW7mcBTM5iuE5dk94TNEfvhacNZCjEwrvBUxSwXNFjUDlOqd8dgPbP2YYN4s8IQQ9sNvAJ/OPD2a8nrtOPacwmZHo2MJhIW1aW5s1P7ltKM9yfGcwOO+2wIGhcDkubkS0pUVFp0K2IkL+9eXplkdpmAWF0BqMYSdHT2qGD+tuBk=,iv:BsjT6Zg/OM1ibWVD+JEpHVGOkj0lxTQoZ+1T8txDiGY=,tag:FWPSB9OQJrRw7MD8rBV5jQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
