apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:04UO4Fd5tnNDLKUEUGYfMfr3w/ZbftrjQS7GK+q+2ApWfX7If30pU2RjUtOCfd/J5C2JzYqXz9KoM7ieqMdzhOi5PHqg3ZGjpNvhkE5nZ1mun3/4o9X6tzeRvY5sQo7rme7zIvVAzGCTOQa2h1PRHIpXw3+Zq/qvuK01JLkqE4BkW7RZwNFjEKSyWMy085lIQCToDZXataMCQnyB2xK9mQbq7OIahmctHF/uxj1BIcrswms/1xSQh6vYuhP9/V92Al+QGA+OCf67shSLflgiC7zlLmBkM6kCKhkGhe9AXQuSUIyz9UjTINLfer/sdBaGMUfUSBaNPpvtuqzYQg1rlO8mXnwRDDKGmeHDk9LefFSjT2CQtRdt1dWvPiyWqaIG,iv:q6P2+719BCffIY6dNEwvK45QSSxdWyP9V8sAtGBTn3w=,tag:ocdD1kWEmBzqmJaxZ1Fpnw==,type:str]
    identity.pub: ENC[AES256_GCM,data:2DLRKdnlQA1xbKeuMnblJS06mVGrso/iZET1oB1XSNCOrgCt5aZITKi/7Kt1SR3s5+JbUCyCM3YaC8tHJxt60vXTMpFEPnI7EbDCnD76q2Z8B1vAwIj2pGF7EKGExX0xQsp/Lg8g1e6F4esLp8T9kVKMnAyVqhjq9suc4dQPRP36vPQVB7kVUGB/RGYBA8MXJvlBfIeBVu0VmITN7HZmlwL2UijW/68hbqmeySHmtEPwBe8jO1h0fXjkI9Hn+kPB1PiA+YotiAGpZfEmSw==,iv:HK3rJgyQxGRSm9Ng3RLVWNduejolk1tHwEmMVZkkMuE=,tag:aTPZq9XZOtRb3zA/EvD16g==,type:str]
    known_hosts: ENC[AES256_GCM,data:m1LthB2+GKWrguY6Z1nLNVw5NfwTQrev5ranBsWgdyjdemVNyQxtZPnNV7NIJLPLyCicmuwq3/oLxtUYeDctJly9NIYWs/YskPRy2sgd5qyxGTdataqvhlNr56vb4BmWRrkQvQNxk2GZM3hxvxF++xTnt9D3edlU0g7dnSonmIeVBTpRDVvIj9hvPQueP7u5+CPlRC2k0E0r1fikKXs2M+FKTlzkqfjKrcUO,iv:v+mYrmbg2shkmjvWOzRzXn3k3cZ/ebuJsYi/3t9ltlU=,tag:cPlxstsurc+gV7Q2tztY6Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17xum3alc55s2l6khaqa2t8twq28cvdl92vfe37pvf69w6gq7rudqqxzu9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aUNwWWZTQTFQdjZQRTZ1
            UDh1UGpsbHlCQ2JBSWRMY0tCcGIrRlE2U21VCjg2dmNHeGcyYU5ZQW4xR3hsQVpT
            Y2dZcEVRaEdKMi93TUpvWXo1MU5hRWsKLS0tIFd5MVoveWFBdUFjb0srM1FrbzU0
            V1I0a0NwUzI4ZW80eEZ3cEZleHYrZVUKcJnO0lEH/Hd7EsTOxBivaiddjsc4XV35
            ck4fWDvCc0mIs9+my0Y3IV1t5TVlg5uVdwG7fy98/qK3UfyWg68SgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-05T16:10:02Z"
    mac: ENC[AES256_GCM,data:PCPgx1VAaHJfIsAOoLkrXGQ79Fynp8F9rOeEzTCuv0qNBzArmD4QdpswrIbgnm29jjCjDy3CUNk1Su9jZpTcYrq+AfM8QeBpSuE+0iBK8eI/T3Va/9U25SKHBk0A5FCciJ153rAUdeT4VqJRDq/lvbvB/XTBHK/kAUobGxyoyho=,iv:+G93I6AGQlhjZfoXe59u/5BO6FTdduDLHc8LB0342ic=,tag:YnIt+SFyItkNtdHzg+3z1g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
