apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 15m
    chart:
        spec:
            chart: nextcloud
            version: 32.0.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: nextcloud
    values:
        TZ: Asia/Shanghai
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        cnpg:
            main:
                # annotations:
                #     cnpg.io/skipEmptyWalArchiveCheck: "enabled"
                backups:
                    enabled: false
                    credentials: cloudflare
                    scheduledBackups:
                        - name: daily-backup
                          schedule: "0 5 0 * * *"
                          backupOwnerReference: self
                          immediate: true
                          suspend: false
                    retentionPolicy: ""
                    revision: "2"
                cluster:
                    instances: 1
                    singleNode: true
                database: nextcloud
                enabled: true
                hibernate: false
                mode: recovery
                monitoring:
                    disableDefaultQueries: false
                    enablePodMonitor: true
                password: ${NEXTCLOUD_CNPG_PASSWORD}
                pgVersion: 16
                pooler:
                    enabled: false
                recovery:
                    credentials: cloudflare
                    method: object_store
                    revision: "1"
                user: nextcloud
        credentials:
            aws:
                accessKey: ${AWS_ACCESSKEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCRKEY}
                name: aws
                path: pvc
                secretKey: ${AWS_SECRETKEY}
                type: s3
                url: ${AWS_URL}
            cloudflare:
                accessKey: ${CF_ACCESSKEY}
                bucket: ${CF_BUCKET}
                encrKey: ${CF_ENCRKEY}
                name: cloudflare
                path: ""
                secretKey: ${CF_SECRETKEY}
                type: s3
                url: ${CF_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: nextcloud.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                required: true
        nextcloud:
            credentials:
                initialAdminPassword: ${NEXTCLOUD_ADMIN_PASSWORD}
                initialAdminUser: ${NEXTCLOUD_ADMIN_USERNAME}
            general:
                accessIP: ${NAS_IP}
                default_phone_region: CN
                force_enable_allow_local_remote_servers: false
                run_optimize: false
            notify_push:
                enabled: true
            previews:
                cron: true
                enabled: true
                providers:
                    - BMP
                    - GIF
                    - JPEG
                    - Krita
                    - MarkDown
                    - MP3
                    - OpenDocument
                    - PNG
                    - TXT
                    - XBitmap
                schedule: '*/30 * * * *'
                square_sizes: 32 256
                width_sizes: 256 384
        persistence:
            config:
                enabled: true
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: true
                      name: config-cloudflare
                      src:
                        enabled: true
                      type: restic
                      trigger:
                        schedule: 10 1 * * *
                    - credentials: aws
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
                      trigger:
                        schedule: 10 1 * * *
            data:
                enabled: true
                path: /${NEXTCLOUD_DATA_PATH}
                server: ${NAS_IP}
                type: nfs
            html:
                enabled: true
