apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 45.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  timeout: 20m
  values:
    TZ: Asia/Shanghai
    cnpg:
      main:
        backups:
          enabled: false
          credentials: cloudflare
          revision: "3"
        cluster:
          instances: 1
          singleNode: true
        database: nextcloud
        enabled: true
        mode: recovery
        password: ${NEXTCLOUD_CNPG_PASSWORD}
        pgVersion: 16
        recovery:
          credentials: cloudflare
          revision: "2"
        user: nextcloud
    credentials:
      cloudflare:
        type: s3
        url: ${CF_URL}
        bucket: ${CF_BUCKET}
        accessKey: ${CF_ACCESSKEY}
        secretKey: ${CF_SECRETKEY}
        encrKey: ${CF_ENCRKEY}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        required: true
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: false
        hosts:
          - host: nextcloud.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    nextcloud:
      credentials:
        initialAdminPassword: ${NEXTCLOUD_ADMIN_PASSWORD}
        initialAdminUser: ${NEXTCLOUD_ADMIN_USERNAME}
      general:
        accessIP: ${NGINX_EXTERNAL_IP}
        default_phone_region: CN
      notify_push:
        enabled: true
      previews:
        enabled: true
        cron: true
        schedule: '*/30 * * * *'
    persistence:
      config:
        enabled: true
        volsync:
          - name: config-cloudflare
            type: restic
            credentials: cloudflare
            dest:
              enabled: true
            src:
              enabled: false
            trigger:
              schedule: 10 1 * * *
      data:
        enabled: true
        type: nfs
        server: ${NAS_IP}
        path: /${NEXTCLOUD_DATA_PATH}
      html:
        enabled: true
    redis:
      enabled: true
      username: default
