apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: qflood
    namespace: qflood
spec:
    interval: 15m
    chart:
        spec:
            chart: qflood
            version: 7.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: qflood
    values:
        TZ: Asia/Shanghai
        ingress:
            main:
                enabled: true
                hosts:
                    - host: qflood.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                enabled: true
                mountPath: /config
            data:
                enabled: true
                mountPath: "/mnt/data"
                type: nfs
                readOnly: false
                autoPermissions:
                    enabled: true
                path: "/${BT_DATA_PATH}"
                server: ${NAS_IP}
        workload:
            main:
                podSpec:
                containers:
                    main:
                    env:
                        FLOOD_AUTH: "${FLOOD_AUTH}"
