apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qflood
  namespace: qflood
spec:
  interval: 15m
  chart:
    spec:
      chart: qflood
      version: 9.9.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Asia/Shanghai
    image:
      repository: ghcr.io/engels74/qflood
      pullPolicy: IfNotPresent
      tag: latest@sha256:008836201603047e4a5cbee13083f3716903b71ee3afc92fcb4d129579f582d7
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: false
        hosts:
          - host: qflood.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
      data:
        enabled: true
        type: nfs
        server: ${NAS_IP}
        path: /${BT_DATA_PATH}
        mountPath: /mnt/data
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FLOOD_AUTH: ${FLOOD_AUTH}
