apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea
    namespace: gitea
spec:
    interval: 15m
    chart:
        spec:
            chart: gitea
            version: 20.13.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: gitea
    values:
        TZ: Asia/Shanghai
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        admin:
            email: ${GITEA_ADMIN_EMAIL}
            password: ${GITEA_ADMIN_PASSWORD}
            username: ${GITEA_ADMIN_USERNAME}
        cnpg:
            main:
                # annotations:
                #     cnpg.io/skipEmptyWalArchiveCheck: "enabled"
                backups:
                    enabled: false
                    credentials: cloudflare
                    scheduledBackups:
                        - name: daily-backup
                          schedule: "0 5 0 * * *"
                          backupOwnerReference: self
                          immediate: true
                          suspend: false
                    retentionPolicy: ""
                    revision: "2"
                cluster:
                    instances: 1
                    singleNode: true
                database: gitea
                enabled: true
                hibernate: false
                mode: recovery
                monitoring:
                    disableDefaultQueries: false
                    enablePodMonitor: true
                password: ${GITEA_CNPG_PASSWORD}
                pgVersion: 16
                pooler:
                    enabled: false
                recovery:
                    credentials: cloudflare
                    method: object_store
                    revision: "1"
                user: gitea
        config:
            ALLOWED_HOST_LIST: 127.0.0.1
            APP_NAME: Gitea
            RUN_MODE: prod
            nodeIP: ${NAS_IP}
        credentials:
            cloudflare:
                accessKey: ${CF_ACCESSKEY}
                bucket: ${CF_BUCKET}
                encrKey: ${CF_ENCRKEY}
                name: cloudflare
                path: ""
                secretKey: ${CF_SECRETKEY}
                type: s3
                url: ${CF_URL}
            aws:
                accessKey: ${AWS_ACCESSKEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCRKEY}
                name: cloudflare
                path: ""
                secretKey: ${AWS_SECRETKEY}
                type: s3
                url: ${AWS_URL}
        customConfig:
            - keys:
                - name: REGISTER_MANUAL_CONFIRM
                  value: "True"
              name: service
            - keys:
                - name: REQUIRE_SIGNIN_VIEW
                  value: "True"
              name: service.explore
            - keys:
                - name: REPOSITORY_AVATAR_FALLBACK
                  value: random
              name: picutre
        ingress:
            main:
                enabled: true
                hosts:
                    - host: gitea.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            data:
                enabled: true
                mountPath: /data
                readOnly: false
                storageClass: ""
                targetSelectAll: true
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: true
                      name: data-cloudflare
                      src:
                        enabled: true
                      type: restic
                      trigger:
                        schedule: 10 1 * * *
                    - credentials: aws
                      dest:
                        enabled: false
                      name: data
                      src:
                        enabled: true
                      type: restic
                      trigger:
                        schedule: 10 1 * * *
