apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openspeedtest
    namespace: openspeedtest
spec:
    interval: 15m
    chart:
        spec:
            chart: openspeedtest
            version: 10.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: openspeedtest
    values:
        TZ: Asia/Shanghai
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        ingress:
            main:
                enabled: true
                hosts:
                    - host: speedtest.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        release_name: openspeedtest
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        workload:
            main:
                podSpec:
                    containers:
                        main: {}
                replicas: 1
                type: Deployment
