apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: portainer
    namespace: portainer
spec:
    interval: 15m
    chart:
        spec:
            chart: portainer
            version: 10.17.3
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: portainer
    values:
        TZ: Asia/Shanghai
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        beImage:
            pullPolicy: IfNotPresent
            repository: portainer/portainer-ee
            tag: 2.20.3@sha256:afadde3ae572f2346d0e04965171f6f1d2f1d06023796053c327e183c75d6cc6
        ingress:
            main:
                enabled: true
                hosts:
                    - host: portainer.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            cache:
                enabled: true
                mountPath: /.cache
                type: emptyDir
            data:
                enabled: true
                mountPath: /data
                readOnly: false
                storageClass: ""
        portainer:
            edge_compute: false
            logo: ""
            snapshot_interval: 5m
        rbac:
            main:
                clusterWide: true
                enabled: true
                primary: true
                rules:
                    - apiGroups:
                        - '*'
                      resources:
                        - '*'
                      verbs:
                        - '*'
        release_name: portainer
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        serviceAccount:
            main:
                enabled: true
                primary: true
        updated: true
        workload:
            main:
                podSpec:
                    automountServiceAccountToken: true
                    containers:
                        main:
                            imageSelector: image
                            probes:
                                liveness:
                                    port: 9443
                                    type: https
                                readiness:
                                    port: 9443
                                    type: https
                                startup:
                                    port: 9443
                                    type: https
                replicas: 1
                type: Deployment
