apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 15m
  chart:
    spec:
      chart: portainer
      version: 10.17.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Asia/Shanghai
    beImage:
      pullPolicy: IfNotPresent
      repository: portainer/portainer-ee
      tag: 2.20.3@sha256:afadde3ae572f2346d0e04965171f6f1d2f1d06023796053c327e183c75d6cc6
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: false
        hosts:
          - host: portainer.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      cache:
        enabled: true
        type: emptyDir
        mountPath: /.cache
      data:
        enabled: true
        mountPath: /data
    portainer:
      edge_compute: false
      snapshot_interval: 5m
    rbac:
      main:
        enabled: true
        primary: true
        clusterWide: true
        rules:
          - apiGroups:
              - '*'
            resources:
              - '*'
            verbs:
              - '*'
    serviceAccount:
      main:
        enabled: true
        primary: true
    workload:
      main:
        replicas: 1
        podSpec:
          automountServiceAccountToken: true
